# Generated by Django 2.2.4 on 2022-10-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the description'),
            preserve_default=False,
        ),
    ]
