# Generated by Django 4.1.2 on 2022-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
    ]
