# Generated by Django 2.2 on 2022-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Bars'), ('P', 'Weights And Plates'), ('E', 'Equipment'), ('C', 'Conditioning'), ('S', 'Storage'), ('G', 'Gear and Accessories'), ('SU', 'Suppliments')], max_length=2),
        ),
    ]
